# Generated by Django 3.1.2 on 2022-02-25 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('name', models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('tableof', models.IntegerField(default=1, null=True)),
                ('reserved', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('arrival', models.DateTimeField(null=True)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tables')),
            ],
        ),
    ]
